#!/usr/bin/env php
<?php

class Console
{
    /** @var array */
    private $bootstrap;

    /** @var \Silex\Application */
    private $app;

    /**
     * Console constructor.
     */
    public function __construct()
    {
        $this->bootstrap = require_once __DIR__ . '/bootstrap.php';
        $this->app = $this->bootstrap['console'];

        $this->addCommandsFromDirectory('/src/Console', 'Console');
        $this->addCommandsFromDirectory('/Auction', 'Auction');
    }

    /**
     * Run console applications.
     */
    public function run()
    {
        $this->app->run();
    }

    /**
     * Register console commands.
     *
     * @param string $path
     * @param string $namespace
     */
    private function addCommandsFromDirectory($path, $namespace)
    {
        foreach (glob(realpath(__DIR__ . "/../") . $path . "/*Command.php") as $filename) {
            $basename = basename($filename, '.php');
            $commandWithNamespace = '\\' . $namespace . '\\' . $basename;

            $this->app->add(new $commandWithNamespace($this->bootstrap));
        }
    }
}

set_time_limit(0);

$console = new Console();
$console->run();

?>